name: Build

on: [push, pull_request]

jobs:
  publish:
    name: Build Binary
    
    strategy:
      matrix:
        target:
        - '{"platform":"win","os":"windows-latest"}'
        - '{"platform":"linux","os":"ubuntu-latest"}'
        - '{"platform":"mac","os":"macos-latest"}'

    runs-on: ${{ fromJson(matrix.target).os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        # fetch-depth: 0

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install Packages
      run: npm i

    - name: TypeScript Build
      run: npm run build

    - name: Electron Build
      run: npx electron-builder -c electron-builder.config.js --${{ fromJson(matrix.target).platform }}

    - name: Remove Unpacked Files
      shell: bash
      run: rm -rf .build/win-unpacked/ .build/mac/ .build/mac-unpacked/ .build/linux-unpacked/

    - name: Push Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kaiheila-uni-${{ fromJson(matrix.target).platform }}-${{ github.sha }}
        path: .build
